name: Deploy Documentation to GitHub Pages

# Define quando o workflow será executado
on:
  push:
    branches:
      - master  # Executa o workflow quando houver push no branch "master"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Define o ambiente de execução

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Clona o repositório

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Especifica a versão do Python (3.11)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the documentation
      run: mkdocs build  # Constrói a documentação

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force  # Faz o deploy para o GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa o token gerado automaticamente
